services:
  fastapi:
    image: dwani/school-server:latest  # Replace with your FastAPI Docker image
    container_name: fastapi_server
    ports:
      - "80:8000"  # Expose FastAPI server port (adjust if needed)
    environment:
      - TUTOR_API_KEY=YourKey
      - DWANI_API_BASE_URL="API_URL"
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Allows access to host's localhost
    restart: unless-stopped

networks:
  app-network:
    driver: bridge